In [3]:
! pip install nltk

  Using cached click-8.3.0-py3-none-any.whl.metadata (2.6 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 22.3 MB/s  0:00:00
Using cached click-8.3.0-py3-none-any.whl (107 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [nltk]2/3 [nltk]


In [1]:
################# Section 1.a ###############

greetGrammar = """
  S -> "hello" | "hi" | "good to see you"
"""

In [4]:
#################### Section 1.b ####################### 
import nltk
from nltk.parse.generate import generate

grammar = nltk.CFG.fromstring(greetGrammar)
print([g for g in generate(grammar)])

[['hello'], ['hi'], ['good to see you']]


In [5]:
#################### Section 1.c ####################### 

greetGrammarWithNames = """
    S -> "Hello" N | "hi" N | "Good to see you" N
    N -> "Alice" | "Bob" | "Charlie"
"""
grammar = nltk.CFG.fromstring(greetGrammarWithNames)
print([g for g in generate(grammar)])

[['Hello', 'Alice'], ['Hello', 'Bob'], ['Hello', 'Charlie'], ['hi', 'Alice'], ['hi', 'Bob'], ['hi', 'Charlie'], ['Good to see you', 'Alice'], ['Good to see you', 'Bob'], ['Good to see you', 'Charlie']]


In [20]:
#################### Section 1.d ####################### 

import random


positive_film_grammar = nltk.CFG.fromstring("""
S -> NP VP | PR VPR                                
NP -> Det N
N -> 'director' | 'screenplay' | 'plot' | 'story' | 'scenes' | 'special effects' | 'costumes' | 'actors' | 'dialogues' | 'characters'
VP -> Verb Adj
                                            
VPR -> VerbPR NP
                                            
Det -> 'the' | 'this' | 'these' | 'those'
                                            
Verb -> 'is' | 'looks' | 'was' | 'are' | 'look' | 'were'
                                            
VerbPR -> 'love' | 'loved' | 'enjoy' | 'enjoyed' | 'fell in love with' | 'adore' | 'adored'
PR -> 'I'
                                            
Adj -> 'great' | 'cool' | 'amazing' | 'fantastic' | 'very nice'
""")

positive_reviews = list(generate(positive_film_grammar))
for i in range(5):
  print(random.choice(positive_reviews))

['those', 'scenes', 'are', 'fantastic']
['the', 'special effects', 'was', 'very nice']
['those', 'costumes', 'are', 'fantastic']
['those', 'characters', 'are', 'great']
['these', 'screenplay', 'look', 'cool']


In [8]:
#################### Section 1.e ####################### 

positive_film_grammar = nltk.CFG.fromstring("""
S -> NP VPS | NPP VPP | PR VPR
NPS -> DetS NS
NPP -> DetP NP
NS -> 'director' | 'screenplay' | 'plot' | 'story' | 'atomsphere' 
NP -> 'scenes' | 'special effects' | 'comstumes' | 'actors' | 'dialogues' | 'characters'

VPS -> VerbS Adj
VPP -> VerbP Adj
VPR -> VerbPR NPS | VerbPR NPP

DetS -> 'the' | 'this' 
DetP -> 'the' | 'these' | 'those'
Verb -> 'is' | 'looks' | 'was' 
VerbP -> 'are' | 'look' | 'were'
VerbPR -> 'love' | 'loved' | 'enjoy' | 'enjoyed' | 'fell in love with' | 'adore' | 'adored'
PR -> 'I'
Adj -> 'great' | 'cool' | 'amazing' | 'fantastic' | 'very nice'
""")

positive_reviews = [' '.join(s) for s in generate(positive_film_grammar)]
for i in range(5):
  print(random.choice(positive_reviews))

I loved those special effects
the characters were great
I enjoyed the atomsphere
I adore the comstumes
these actors look great


In [14]:
#################### Section 1.f ####################### 

negative_film_grammar = nltk.CFG.fromstring("""
S -> NP VPS | NPP VPP | PR VPR
NPS -> DetS NS
NPP -> DetP NP
NS -> 'director' | 'screenplay' | 'plot' | 'story' | 'atomsphere' 
NP -> 'scenes' | 'special effects' | 'comstumes' | 'actors' | 'dialogues' | 'characters'

VPS -> VerbS Adj
VPP -> VerbP Adj
VPR -> VerbPR NPS | VerbPR NPP

DetS -> 'the' | 'this' 
DetP -> 'the' | 'these' | 'those'
Verb -> 'is' | 'looks' | 'was' 
VerbP -> 'are' | 'look' | 'were'
VerbPR -> 'hate' | 'hated' | 'do not liek' | 'did not enjoy' | 'got bored with' | 'despise' | 'despised'
PR -> 'I'
Adj -> 'medicore' | 'dull' | 'terrible' | 'boring' | 'lame' | 'dump'
""")

negative_reviews = [' '.join(s) for s in generate(negative_film_grammar)]
for i in range(5):
  print(random.choice(negative_reviews))

those comstumes look dump
I despise the actors
I hate the director
these comstumes look terrible
those characters are terrible


In [26]:
#################### Section 1.g ####################### 

grammar_training_dataset = []
for i in range(1000):
  positive_utterance = f"{random.choice(positive_reviews)}. {random.choice(positive_reviews)}. {random.choice(positive_reviews)}"
  negative_utterance = f"{random.choice(negative_reviews)}. {random.choice(negative_reviews)}. {random.choice(negative_reviews)}"
  grammar_training_dataset.append((positive_utterance, "pos"))
  grammar_training_dataset.append((negative_utterance, "neg"))

for i in range(5):
  print(random.choice(grammar_training_dataset))

("['these', 'story', 'is', 'fantastic']. ['this', 'actors', 'looks', 'fantastic']. ['those', 'actors', 'are', 'amazing']", 'pos')
('those actors look terrible. I despise this director. I hate the screenplay', 'neg')
('those scenes look dull. those dialogues look terrible. I hate this atomsphere', 'neg')
('I despise those comstumes. I despise the director. those actors look lame', 'neg')
('the dialogues were boring. those comstumes look boring. I hate those special effects', 'neg')


In [9]:
#################### Section 2.1.a ####################### 

import regex as re

input_text = "We hold these truths to be self-evident, that all men are created equal, that all men are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness and mental stability."

re.sub(r"\bmen\b", "people", input_text)


'We hold these truths to be self-evident, that all people are created equal, that all people are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness and mental stability.'

In [10]:
#################### Section 2.1.b ####################### 

nltk.download('movie_reviews')

from nltk.corpus import movie_reviews

nltk_data = []
for file_id in movie_reviews.fileids():
  nltk_data.append((movie_reviews.raw(file_id), movie_reviews.categories(file_id)[0]))

print(len(nltk_data))

[nltk_data] Downloading package movie_reviews to
[nltk_data]     /Users/saki/nltk_data...
[nltk_data]   Unzipping corpora/movie_reviews.zip.


2000


In [11]:
#################### Section 2.1.c ####################### 

import regex as re

def cleanup_review(review):
############## TO DO PART ###############
  # 1. Replace all URLs with URLTOKEN
  review = re.sub(r'http\S+', 'URLTOKEN', review)
  # 2. Replace all dates with DATETOKEN
  review = re.sub(r"\d{4}-\d{2}-\d{2}","DATETOKEN", review)
  review = re.sub(r"\d{4}/\d{2}/\d{2}","DATETOKEN", review)

  review = re.sub(r"\d{2}-\d{2}-\d{4}","DATETOKEN", review)
  review = re.sub(r"\d{2}/\d{2}/\d{4}","DATETOKEN", review)
  # 3. Remove all non-alphanumerical characters
  review = re.sub(r"[^a-zA-Z0-9,!.\';:? ]","", review)
  # 4. Collapse multiple spaces into one space
  review = re.sub(r'\s\s+', ' ', review)
  return review


cleanup_review("Hello!! My name is Stefano, I have been a tutor for COMP~9414 since 01/04/2023. My personal website is http://stefano.com . (Nice to meet you ^__^)")

'Hello!! My name is Stefano, I have been a tutor for COMP9414 since DATETOKEN. My personal website is URLTOKEN . Nice to meet you '

In [12]:
#################### Section 2.2 ####################### 

import numpy as np
np.random.seed(999)

cleanup_data = [(cleanup_review(r), l) for r,l in nltk_data]

np.random.shuffle(cleanup_data)

train_nltk_data = cleanup_data[0:int(len(cleanup_data)*0.85)]
test_nltk_data = cleanup_data[int(len(cleanup_data)*0.85):int(len(cleanup_data)*0.95)]
valid_nltk_data = cleanup_data[int(len(cleanup_data)*0.95):]

In [16]:
#################### Section 3.a ####################### 

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline

#### TO DO #########

pipeline = Pipeline([
  ('vect', TfidfVectorizer(min_df=3, max_df=0.95)),
  ('clf', LinearSVC(C=1000, max_iter=10000)),
])

In [27]:
#################### Section 3.b ####################### 

pipeline.fit([d[0] for d in grammar_training_dataset], [d[1] for d in grammar_training_dataset])

Pipeline(steps=[('vect', TfidfVectorizer(max_df=0.95, min_df=3)),
                ('clf', AdaBoostClassifier())])

In [28]:
#################### Section 3.c ####################### 

from sklearn import metrics

y_predicted = pipeline.predict([t[0] for t in test_nltk_data])

# Print the classification report
print(metrics.classification_report([t[1] for t in test_nltk_data], y_predicted,
                                    target_names=['positive', 'negative']))

              precision    recall  f1-score   support

    positive       0.54      0.39      0.45       111
    negative       0.44      0.60      0.50        89

    accuracy                           0.48       200
   macro avg       0.49      0.49      0.48       200
weighted avg       0.50      0.48      0.48       200



Here the results might not be very good as you trained your pipeline with grammar_training_dataset and you are testing it with test_nltk_data. 

In [22]:
#################### Section 3.d ####################### 

####### TO DO ###########
pipeline = Pipeline([
    ('vect', TfidfVectorizer(min_df=3, max_df=0.95)),
    ('clf', LinearSVC(C=1000, max_iter=10000)),
])

pipeline.fit([d[0] for d in train_nltk_data], [d[1] for d in train_nltk_data])

Pipeline(steps=[('vect', TfidfVectorizer(max_df=0.95, min_df=3)),
                ('clf', LinearSVC(C=1000, max_iter=10000))])

In [23]:
#################### Section 3.e ####################### 

from sklearn import metrics

###### TO DO ######
y_predicted = pipeline.predict([t[0] for t in test_nltk_data])
# Print the classification report
print(metrics.classification_report([t[1] for t in test_nltk_data], y_predicted,
                                    target_names=['positive', 'negative']))

              precision    recall  f1-score   support

    positive       0.88      0.86      0.87       111
    negative       0.83      0.85      0.84        89

    accuracy                           0.85       200
   macro avg       0.85      0.85      0.85       200
weighted avg       0.86      0.85      0.86       200



In [29]:
#################### Section 3.f ####################### 
# 3.f (i) grammar_training_dataset and nltk_data combined

###### TO DO ######
pipeline=Pipeline([
  ('vect', TfidfVectorizer(min_df=3, max_df=0.95)),
  ('clf', LinearSVC(C=1000, max_iter=10000)),
])
pipeline.fit([d[0] for d in train_nltk_data+grammar_training_dataset],[d[1] for d in train_nltk_data + grammar_training_dataset])

y_predicted = pipeline.predict([t[0] for t in test_nltk_data])
print(metrics.classification_report([t[1] for t in test_nltk_data], y_predicted,
                                    target_names=['positive', 'negative']))

              precision    recall  f1-score   support

    positive       0.89      0.84      0.87       111
    negative       0.81      0.88      0.84        89

    accuracy                           0.85       200
   macro avg       0.85      0.86      0.85       200
weighted avg       0.86      0.85      0.86       200



In [25]:
#################### Section 3.f ####################### 
# 3.f (ii) classifiers experiments

from sklearn.datasets import make_circles, make_classification, make_moons
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.inspection import DecisionBoundaryDisplay
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

classifiers = [
    KNeighborsClassifier(3),
    SVC(gamma=2, C=1),
    DecisionTreeClassifier(max_depth=5),
    RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1),
    MLPClassifier(alpha=1, max_iter=1000),
    AdaBoostClassifier()
]


###### TO DO ######
for c in classifiers:
  print(f"Training classifier model: {c.__str__()}")
  pipeline=Pipeline([
    ('vect', TfidfVectorizer(min_df=3, max_df=0.95)),
    ('clf', c)
  ])
  pipeline.fit(np.array([d[0] for d in train_nltk_data]), np.array([d[1] for d in train_nltk_data]))
  y_predicted = pipeline.predict([t[0] for t in valid_nltk_data])
  print(metrics.classification_report([t[1] for t in valid_nltk_data], y_predicted,
                                    target_names=['positive', 'negative']))

Training classifier model: KNeighborsClassifier(n_neighbors=3)
              precision    recall  f1-score   support

    positive       0.79      0.69      0.74        55
    negative       0.67      0.78      0.72        45

    accuracy                           0.73       100
   macro avg       0.73      0.73      0.73       100
weighted avg       0.74      0.73      0.73       100

Training classifier model: SVC(C=1, gamma=2)
              precision    recall  f1-score   support

    positive       0.89      0.87      0.88        55
    negative       0.85      0.87      0.86        45

    accuracy                           0.87       100
   macro avg       0.87      0.87      0.87       100
weighted avg       0.87      0.87      0.87       100

Training classifier model: DecisionTreeClassifier(max_depth=5)
              precision    recall  f1-score   support

    positive       0.67      0.53      0.59        55
    negative       0.54      0.69      0.61        45

    accurac

In [ ]:
Q
[2 0]
[1 2]
[1 2]

K
[2 1]
[0 3]
[3 1]

V
[1 2]
[2 1]
[3 2]

Q . Kt
[4 0 6]
[4 6 5]
[4 6 5]

dimentiom Dk = 2

(Q . Kt)/(Dk ^ 1/2)
[2.83   0  4.24]
[2.83 4.24 3.59]
[2.83 4.24 3.59]

softmax: ezi / sigma_j(eij)
[e^2.83 e^  0  e^4.24]=87.34   [0.19 0.01 0.79]
[e^2.83 e^4.24 e^3.59]=120.8 = [0.19 0.57 0.29]
[e^2.83 e^4.24 e^3.59]=120.8   [0.19 0.57 0.29]

softmax[(Q . Kt)/(Dk ^ 1/2)] . V
[2.58 1.97]
[2.15 1.93]
[2.15 1.93]