In [9]:
import gymnasium as gym
import numpy as np

env=gym.make("FrozenLake-v1",render_mode="rgb_array", is_slippery=False)
n_states = env.observation_space.n
n_actions = env.action_space.n

Q =np.zeros((n_states,n_actions))

alpha = 0.8
gamma = 0.95
epsilon =1.0
epsilon_min =0.01
epsilon_decay = 0.995
epsodes = 4000
max_steps = 100

for ep in range(epsodes):
    s,_ =env.reset()
    done = False
    for _ in range(max_steps):
        if np.random.rand()< epsilon:
            a = env.action_space.sample()
        else:
            a =np.argmax(Q[s])
        s_next,r,term,trunc,_ = env.step(a)
        done = term or trunc

        Q[s,a]=Q[s,a]+ alpha * (r + gamma * np.max(Q[s_next])-Q[s,a])

        s= s_next
        if done:
            break
    if epsilon > epsilon_min:
        epsilon *= epsilon_decay

print('finish')
print(Q)


finish
[[0.73509189 0.77378094 0.6983373  0.73509189]
 [0.73509189 0.         0.66340364 0.69833727]
 [0.69833652 0.42141696 0.         0.37305976]
 [0.53066248 0.         0.         0.        ]
 [0.77378094 0.81450625 0.         0.73509189]
 [0.         0.         0.         0.        ]
 [0.         0.90249554 0.         0.52889367]
 [0.         0.         0.         0.        ]
 [0.81450625 0.         0.857375   0.77378094]
 [0.81450625 0.9025     0.9025     0.        ]
 [0.85656096 0.95       0.         0.85728065]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9025     0.95       0.857375  ]
 [0.9025     0.95       1.         0.9025    ]
 [0.         0.         0.         0.        ]]


In [5]:
! pip install pygame

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 33.8 MB/s  0:00:00eta 0:00:01


In [ ]:
env = gym.make("FrozenLake-v1",render_mode="human")
s, _ = env.reset()
done = False
total_reward = 0
while not done:
    a=np.argmax(Q[s])
    s,r,term,trunc, _ = env.step(a)
    print(a)
    total_reward += r
    env.render()
    done = term or trunc
print(total_reward)
env.close()

1
0
1
0
0
0.0


: 